from datetime import datetime
from enum import Enum
from typing import Any

from databricks.labs.dqx.config import RunConfig, WorkspaceConfig
from pydantic import BaseModel, Field

from .. import __version__


# =============================================================================
# Enums
# =============================================================================

class UserRole(str, Enum):
    ADMIN = "admin"
    DATA_STEWARD = "data_steward"
    VIEWER = "viewer"


class RuleStatus(str, Enum):
    DRAFT = "draft"
    PENDING_APPROVAL = "pending_approval"
    APPROVED = "approved"
    EXPORTED = "exported"
    REJECTED = "rejected"


class ProfileStatus(str, Enum):
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


# =============================================================================
# Version
# =============================================================================

class VersionOut(BaseModel):
    version: str

    @classmethod
    def from_metadata(cls):
        return cls(version=__version__)


# =============================================================================
# Legacy Config Models (for backward compatibility)
# =============================================================================

class ConfigOut(BaseModel):
    config: WorkspaceConfig


class ConfigIn(BaseModel):
    config: WorkspaceConfig


class RunConfigOut(BaseModel):
    config: RunConfig


class RunConfigIn(BaseModel):
    config: RunConfig


class ChecksOut(BaseModel):
    checks: list[dict[str, Any]]


class ChecksIn(BaseModel):
    checks: list[dict[str, Any]]


class InstallationSettings(BaseModel):
    install_folder: str = Field(description="Path to the folder containing config.yml")


class GenerateChecksIn(BaseModel):
    user_input: str = Field(description="Natural language description of data quality requirements")


class GenerateChecksOut(BaseModel):
    yaml_output: str = Field(description="Generated checks in YAML format")
    checks: list[dict[str, Any]] = Field(description="Generated checks as a list of dictionaries")


# =============================================================================
# New App Settings Models (View-Based Approach)
# =============================================================================

class AppSettings(BaseModel):
    """App-level settings stored in dq_app_settings table."""
    target_catalog: str = Field(description="User-selected catalog for DQX app storage")
    target_schema: str = Field(default="dqx_app", description="Schema created by app within the catalog")
    data_steward_group: str | None = Field(default=None, description="Group for data steward permissions")
    viewer_group: str | None = Field(default=None, description="Group for viewer permissions")
    initialized: bool = Field(default=False, description="Whether the app has been initialized")
    initialized_at: datetime | None = Field(default=None, description="When the app was initialized")
    initialized_by: str | None = Field(default=None, description="User who initialized the app")


class InitializeRequest(BaseModel):
    """Request to initialize the app's schema, tables, and permissions."""
    target_catalog: str = Field(description="Catalog to create the dqx_app schema in")
    target_schema: str = Field(default="dqx_app", description="Schema name to create")
    data_steward_group: str = Field(description="Group for data steward permissions")
    viewer_group: str | None = Field(default=None, description="Group for viewer permissions (optional)")


class InitializeResponse(BaseModel):
    """Response from app initialization."""
    success: bool
    schema_created: bool
    tables_created: list[str]
    grants_applied: list[str]
    errors: list[str]


class PrerequisiteSqlResponse(BaseModel):
    """Response with prerequisite SQL for catalog owner."""
    sql: str
    instructions: list[str]


# =============================================================================
# Profiling Models
# =============================================================================

class ProfileTableRequest(BaseModel):
    """Request to profile a table."""
    catalog: str = Field(description="Source table catalog")
    schema_name: str = Field(description="Source table schema")
    table: str = Field(description="Source table name")
    sample_fraction: float | None = Field(default=0.1, description="Fraction of data to sample (0.0-1.0)")
    sample_limit: int | None = Field(default=50000, description="Maximum number of rows to sample")
    columns: list[str] | None = Field(default=None, description="Specific columns to profile (None = all)")


class GeneratedRule(BaseModel):
    """A rule generated by the profiler."""
    name: str = Field(description="Rule name/identifier")
    check_type: str = Field(description="Type of check (e.g., is_not_null, min_max)")
    column: str = Field(description="Column the rule applies to")
    criticality: str = Field(default="error", description="Rule criticality level")
    params: dict[str, Any] = Field(default_factory=dict, description="Rule parameters")


class ProfileJobResponse(BaseModel):
    """Response after submitting a profile job."""
    profile_id: str
    view_name: str
    status: str
    error: str | None = Field(default=None, description="Error message if profiling failed")
    rows_profiled: int | None = Field(default=None, description="Number of rows profiled")
    columns_profiled: int | None = Field(default=None, description="Number of columns profiled")
    duration_seconds: float | None = Field(default=None, description="Profiling duration in seconds")
    generated_rules: list[GeneratedRule] | None = Field(default=None, description="Rules generated from profiling")


class ProfilingResult(BaseModel):
    """A profiling result stored in dq_profiling_results table."""
    profile_id: str
    requesting_user: str
    source_catalog: str
    source_schema: str
    source_table: str
    source_table_fqn: str
    sample_fraction: float | None
    sample_limit: int | None
    profiler_options_json: str | None
    profile_summary_json: str | None
    column_profiles_json: str | None
    rows_profiled: int | None
    columns_profiled: int | None
    profile_duration_seconds: float | None
    created_at: datetime
    status: ProfileStatus
    job_run_id: int | None
    view_name: str | None


class ExistingProfilesResponse(BaseModel):
    """Response showing existing profiles for a table."""
    table: str
    existing_profiles: list[dict[str, Any]]
    has_existing_profiles: bool


# =============================================================================
# Quality Rules Models
# =============================================================================

class QualityRule(BaseModel):
    """A quality rule stored in dq_quality_rules table."""
    rule_id: str
    created_by: str
    approved_by: str | None
    source_catalog: str
    source_schema: str
    source_table: str
    source_table_fqn: str
    rules_json: str
    rules_count: int
    suggestion_id: str | None
    created_at: datetime
    updated_at: datetime | None
    approved_at: datetime | None
    status: RuleStatus
    exported_to: str | None
    exported_at: datetime | None


class CreateRuleRequest(BaseModel):
    """Request to create a new quality rule."""
    source_catalog: str
    source_schema: str
    source_table: str
    rules: list[dict[str, Any]]
    suggestion_id: str | None = None


class UpdateRuleRequest(BaseModel):
    """Request to update an existing quality rule."""
    rules: list[dict[str, Any]]


class RuleResponse(BaseModel):
    """Response for a single rule."""
    rule: QualityRule


class RulesListResponse(BaseModel):
    """Response for listing rules."""
    rules: list[QualityRule]
    total: int


class RuleFilterOptions(BaseModel):
    """Available filter options for rules."""
    catalogs: list[str] = Field(default_factory=list, description="Unique source catalogs")
    schemas: list[str] = Field(default_factory=list, description="Unique source schemas")
    tables: list[str] = Field(default_factory=list, description="Unique source tables")


class ApprovalRequest(BaseModel):
    """Request to approve or reject a rule."""
    action: str = Field(description="'approve' or 'reject'")
    comment: str | None = Field(default=None, description="Optional comment")


class ExportRuleRequest(BaseModel):
    """Request to export a rule to checks storage."""
    checks_location: str = Field(description="Where to export the rules (delta table path)")


# =============================================================================
# Validation Run Models
# =============================================================================

class DryRunRequest(BaseModel):
    """Request to run a dry run validation."""
    sample_size: int = Field(default=10000, description="Number of rows to sample for dry run")


class ValidationRunResult(BaseModel):
    """A validation run result stored in dq_validation_runs table."""
    run_id: str
    rule_id: str
    requesting_user: str
    source_table_fqn: str
    total_rows: int | None
    passed_rows: int | None
    failed_rows: int | None
    rule_results_json: str | None
    sample_failures_json: str | None
    sample_size: int | None
    executed_at: datetime
    duration_seconds: float | None


class DryRunResponse(BaseModel):
    """Response from a dry run."""
    run_id: str
    total_rows: int
    passed_rows: int
    failed_rows: int
    pass_rate: float
    rule_results: list[dict[str, Any]]
    sample_failures: list[dict[str, Any]] | None


# =============================================================================
# Generic Response Models
# =============================================================================

class MessageResponse(BaseModel):
    """Generic response with a message."""
    message: str
    success: bool = True


class CatalogInfo(BaseModel):
    """Information about a catalog."""
    name: str
    has_create_schema: bool = True


class AvailableCatalogsResponse(BaseModel):
    """Response with list of catalogs user can use."""
    catalogs: list[CatalogInfo]
    error: str | None = None


class SchemaInfo(BaseModel):
    """Information about a schema."""
    name: str
    catalog: str


class AvailableSchemasResponse(BaseModel):
    """Response with list of schemas in a catalog."""
    schemas: list[SchemaInfo]
    error: str | None = None


class TableInfo(BaseModel):
    """Information about a table."""
    name: str
    catalog: str
    schema_name: str
    table_type: str | None = None


class AvailableTablesResponse(BaseModel):
    """Response with list of tables in a schema."""
    tables: list[TableInfo]
    error: str | None = None
