import sys

import pytest

from databricks.labs.dqx.config import (
    InputConfig,
    InstallationChecksStorageConfig,
    ProfilerConfig,
    RunConfig,
    WorkspaceFileChecksStorageConfig,
)
from databricks.labs.dqx.engine import DQEngine
from databricks.labs.dqx.profiler.generator import DQGenerator
from databricks.labs.dqx.profiler.profiler import DQProfiler
from databricks.labs.dqx.profiler.profiler_runner import ProfilerRunner
from databricks.labs.dqx.profiler.profiler_workflow import ProfilerWorkflow

from tests.constants import TEST_CATALOG


def test_profiler_runner_raise_error_when_profile_summary_stats_file_missing(ws, spark, installation_ctx):
    profiler = DQProfiler(ws)
    dq_engine = DQEngine(ws, spark)
    runner = ProfilerRunner(ws, spark, dq_engine, installation_ctx.installation, profiler)

    checks = [
        {
            "name": "col_a_is_null_or_empty",
            "criticality": "error",
            "check": {"function": "is_not_null_and_not_empty", "arguments": {"column": "a"}},
        },
    ]
    summary_stats = {
        'a': {
            'count': 3,
            'mean': 2.0,
            'stddev': 1.0,
            'min': 1,
            '25%': 1,
            '50%': 2,
            '75%': 3,
            'max': 3,
            'count_non_null': 3,
            'count_null': 0,
        }
    }
    install_folder = installation_ctx.installation.install_folder()
    checks_location = f"{install_folder}/checks.yml"
    profile_summary_stats_file = "profile_summary_stats.yml"
    storage_config = WorkspaceFileChecksStorageConfig(location=checks_location)

    runner.save(checks, summary_stats, storage_config, profile_summary_stats_file)

    checks_location_status = ws.workspace.get_status(f"{checks_location}")
    assert checks_location_status, f"Checks not uploaded to {checks_location}."

    summary_stats_file_status = ws.workspace.get_status(f"{install_folder}/{profile_summary_stats_file}")
    assert (
        summary_stats_file_status
    ), f"Profile summary stats not uploaded to {install_folder}/{profile_summary_stats_file}."


@pytest.mark.parametrize(
    "configured_criticality, expected_criticality",
    [(None, "error"), ("warn", "warn")],
)
def test_profiler_runner_applies_configured_criticality(
    ws, spark, installation_ctx, make_schema, make_table, configured_criticality, expected_criticality
) -> None:
    """ProfilerConfig.criticality controls the criticality of all rules the profiler generates.

    When `criticality` is not set, ProfilerConfig defaults to "error". When set to "warn",
    every generated rule must come back as "warn".
    """
    installation_ctx.installation.save(installation_ctx.config)

    schema = make_schema(catalog_name=TEST_CATALOG)
    input_table = make_table(
        catalog_name=TEST_CATALOG,
        schema_name=schema.name,
        ctas="SELECT * FROM VALUES (1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e') AS data(id, name)",
    )

    # sample_fraction=1.0 disables sampling. ProfilerConfig's default (0.3) is probabilistic
    # and with only 5 test rows the sample can return 0 rows (~17% of runs: 0.7^5 ≈ 0.168),
    # which makes the profiler generate no rules and this test flake.
    profiler_kwargs: dict = {"sample_fraction": 1.0}
    if configured_criticality is not None:
        profiler_kwargs["criticality"] = configured_criticality

    run_config = RunConfig(
        name="default",
        input_config=InputConfig(location=input_table.full_name),
        profiler_config=ProfilerConfig(**profiler_kwargs),
    )

    profiler = DQProfiler(ws)
    generator = DQGenerator(ws, spark)
    dq_engine = DQEngine(ws, spark)
    runner = ProfilerRunner(ws, spark, dq_engine, installation_ctx.installation, profiler)

    runner.run(
        generator=generator,
        run_config=run_config,
        product=installation_ctx.installation.product(),
        install_folder=installation_ctx.installation.install_folder(),
    )

    storage_config = InstallationChecksStorageConfig(
        run_config_name=run_config.name,
        assume_user=True,
        product_name=installation_ctx.installation.product(),
        install_folder=installation_ctx.installation.install_folder(),
    )
    loaded_checks = dq_engine.load_checks(config=storage_config)

    assert loaded_checks, "Expected at least one rule to be generated by the profiler"
    assert all(
        check["criticality"] == expected_criticality for check in loaded_checks
    ), f"Expected all rules to have criticality '{expected_criticality}', got {[c['criticality'] for c in loaded_checks]}"


def test_profiler_workflow_class(ws, spark_keep_alive, setup_workflows):
    installation_ctx, run_config = setup_workflows()
    spark = spark_keep_alive.spark

    sys.modules["pyspark.sql.session"] = spark
    ctx = installation_ctx.replace(run_config_name=run_config.name)

    ProfilerWorkflow().profile(ctx)  # type: ignore

    config = InstallationChecksStorageConfig(
        run_config_name=run_config.name,
        assume_user=True,
        product_name=installation_ctx.installation.product(),
    )
    checks = DQEngine(ws).load_checks(config=config)

    assert checks, "Checks were not loaded correctly"


def test_profiler_workflow_class_serverless(ws, spark_keep_alive, setup_serverless_workflows):
    installation_ctx, run_config = setup_serverless_workflows()
    spark = spark_keep_alive.spark

    sys.modules["pyspark.sql.session"] = spark
    ctx = installation_ctx.replace(run_config_name=run_config.name)

    ProfilerWorkflow().profile(ctx)  # type: ignore

    config = InstallationChecksStorageConfig(
        run_config_name=run_config.name,
        assume_user=True,
        product_name=installation_ctx.installation.product(),
    )
    checks = DQEngine(ws).load_checks(config=config)

    assert checks, "Checks were not loaded correctly"
