command:
- uvicorn
- databricks_labs_dqx_app.backend.app:app
- --workers
- 2
env:
- name: DATABRICKS_WAREHOUSE_ID
  value: 13df5a7f4c61072a
- name: DQX_CATALOG
  value: uc_cjp_qa
- name: DQX_SCHEMA
  value: dqx_app
- name: DQX_JOB_ID
  value_from: dqx-task-runner-job
- name: DQX_TMP_SCHEMA
  value: dqx_app_tmp
- name: DQX_ADMIN_GROUP
  value: admins
- name: DQX_WHEELS_VOLUME
  value: wheels
- name: DQX_LAKEBASE_INSTANCE_NAME
  value: dqx-studio-lakebase
- name: DQX_LAKEBASE_DATABASE_NAME
  value: databricks_postgres
