/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as SidebarRunsRouteImport } from './../routes/_sidebar/runs'
import { Route as SidebarRulesRouteImport } from './../routes/_sidebar/rules'
import { Route as SidebarProfilerRouteImport } from './../routes/_sidebar/profiler'
import { Route as SidebarProfileRouteImport } from './../routes/_sidebar/profile'
import { Route as SidebarConfigRouteImport } from './../routes/_sidebar/config'
import { Route as SidebarRunsIndexRouteImport } from './../routes/_sidebar/runs.index'
import { Route as SidebarRunsRunNameRouteImport } from './../routes/_sidebar/runs.$runName'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarRunsRoute = SidebarRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarRulesRoute = SidebarRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarProfilerRoute = SidebarProfilerRouteImport.update({
  id: '/profiler',
  path: '/profiler',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarProfileRoute = SidebarProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarConfigRoute = SidebarConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarRunsIndexRoute = SidebarRunsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarRunsRoute,
} as any)
const SidebarRunsRunNameRoute = SidebarRunsRunNameRouteImport.update({
  id: '/$runName',
  path: '/$runName',
  getParentRoute: () => SidebarRunsRoute,
} as any)

// Define children objects BEFORE they are used
const SidebarRunsRouteChildren = {
  SidebarRunsIndexRoute: SidebarRunsIndexRoute,
  SidebarRunsRunNameRoute: SidebarRunsRunNameRoute,
}

const SidebarRunsRouteWithChildren = SidebarRunsRoute._addFileChildren(
  SidebarRunsRouteChildren,
)

const SidebarRouteRouteChildren = {
  SidebarConfigRoute: SidebarConfigRoute,
  SidebarProfileRoute: SidebarProfileRoute,
  SidebarProfilerRoute: SidebarProfilerRoute,
  SidebarRulesRoute: SidebarRulesRoute,
  SidebarRunsRoute: SidebarRunsRouteWithChildren,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config': typeof SidebarConfigRoute
  '/profile': typeof SidebarProfileRoute
  '/profiler': typeof SidebarProfilerRoute
  '/rules': typeof SidebarRulesRoute
  '/runs': typeof SidebarRunsRouteWithChildren
  '/runs/$runName': typeof SidebarRunsRunNameRoute
  '/runs/': typeof SidebarRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config': typeof SidebarConfigRoute
  '/profile': typeof SidebarProfileRoute
  '/profiler': typeof SidebarProfilerRoute
  '/rules': typeof SidebarRulesRoute
  '/runs/$runName': typeof SidebarRunsRunNameRoute
  '/runs': typeof SidebarRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/config': typeof SidebarConfigRoute
  '/_sidebar/profile': typeof SidebarProfileRoute
  '/_sidebar/profiler': typeof SidebarProfilerRoute
  '/_sidebar/rules': typeof SidebarRulesRoute
  '/_sidebar/runs': typeof SidebarRunsRouteWithChildren
  '/_sidebar/runs/$runName': typeof SidebarRunsRunNameRoute
  '/_sidebar/runs/': typeof SidebarRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config'
    | '/profile'
    | '/profiler'
    | '/rules'
    | '/runs'
    | '/runs/$runName'
    | '/runs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/config' | '/profile' | '/profiler' | '/rules' | '/runs/$runName' | '/runs'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/_sidebar/config'
    | '/_sidebar/profile'
    | '/_sidebar/profiler'
    | '/_sidebar/rules'
    | '/_sidebar/runs'
    | '/_sidebar/runs/$runName'
    | '/_sidebar/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_sidebar"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_sidebar": {
      "filePath": "_sidebar/route.tsx",
      "children": [
        "/_sidebar/config",
        "/_sidebar/profile",
        "/_sidebar/profiler",
        "/_sidebar/rules",
        "/_sidebar/runs"
      ]
    },
    "/_sidebar/config": {
      "filePath": "_sidebar/config.tsx",
      "parent": "/_sidebar"
    },
    "/_sidebar/profile": {
      "filePath": "_sidebar/profile.tsx",
      "parent": "/_sidebar"
    },
    "/_sidebar/profiler": {
      "filePath": "_sidebar/profiler.tsx",
      "parent": "/_sidebar"
    },
    "/_sidebar/rules": {
      "filePath": "_sidebar/rules.tsx",
      "parent": "/_sidebar"
    },
    "/_sidebar/runs": {
      "filePath": "_sidebar/runs.tsx",
      "parent": "/_sidebar",
      "children": [
        "/_sidebar/runs/",
        "/_sidebar/runs/$runName"
      ]
    },
    "/_sidebar/runs/": {
      "filePath": "_sidebar/runs.index.tsx",
      "parent": "/_sidebar/runs"
    },
    "/_sidebar/runs/$runName": {
      "filePath": "_sidebar/runs.$runName.tsx",
      "parent": "/_sidebar/runs"
    }
  }
}
ROUTE_MANIFEST_END */
