/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as SidebarRunsRouteImport } from './../routes/_sidebar/runs'
import { Route as SidebarProfileRouteImport } from './../routes/_sidebar/profile'
import { Route as SidebarConfigRouteImport } from './../routes/_sidebar/config'
import { Route as SidebarRunsIndexRouteImport } from './../routes/_sidebar/runs.index'
import { Route as SidebarRunsRunNameRouteImport } from './../routes/_sidebar/runs.$runName'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarRunsRoute = SidebarRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarProfileRoute = SidebarProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarConfigRoute = SidebarConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarRunsIndexRoute = SidebarRunsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarRunsRoute,
} as any)
const SidebarRunsRunNameRoute = SidebarRunsRunNameRouteImport.update({
  id: '/$runName',
  path: '/$runName',
  getParentRoute: () => SidebarRunsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config': typeof SidebarConfigRoute
  '/profile': typeof SidebarProfileRoute
  '/runs': typeof SidebarRunsRouteWithChildren
  '/runs/$runName': typeof SidebarRunsRunNameRoute
  '/runs/': typeof SidebarRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config': typeof SidebarConfigRoute
  '/profile': typeof SidebarProfileRoute
  '/runs/$runName': typeof SidebarRunsRunNameRoute
  '/runs': typeof SidebarRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/config': typeof SidebarConfigRoute
  '/_sidebar/profile': typeof SidebarProfileRoute
  '/_sidebar/runs': typeof SidebarRunsRouteWithChildren
  '/_sidebar/runs/$runName': typeof SidebarRunsRunNameRoute
  '/_sidebar/runs/': typeof SidebarRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config'
    | '/profile'
    | '/runs'
    | '/runs/$runName'
    | '/runs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/config' | '/profile' | '/runs/$runName' | '/runs'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/_sidebar/config'
    | '/_sidebar/profile'
    | '/_sidebar/runs'
    | '/_sidebar/runs/$runName'
    | '/_sidebar/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/runs': {
      id: '/_sidebar/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof SidebarRunsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/profile': {
      id: '/_sidebar/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SidebarProfileRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/config': {
      id: '/_sidebar/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof SidebarConfigRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/runs/': {
      id: '/_sidebar/runs/'
      path: '/'
      fullPath: '/runs/'
      preLoaderRoute: typeof SidebarRunsIndexRouteImport
      parentRoute: typeof SidebarRunsRoute
    }
    '/_sidebar/runs/$runName': {
      id: '/_sidebar/runs/$runName'
      path: '/$runName'
      fullPath: '/runs/$runName'
      preLoaderRoute: typeof SidebarRunsRunNameRouteImport
      parentRoute: typeof SidebarRunsRoute
    }
  }
}

interface SidebarRunsRouteChildren {
  SidebarRunsRunNameRoute: typeof SidebarRunsRunNameRoute
  SidebarRunsIndexRoute: typeof SidebarRunsIndexRoute
}

const SidebarRunsRouteChildren: SidebarRunsRouteChildren = {
  SidebarRunsRunNameRoute: SidebarRunsRunNameRoute,
  SidebarRunsIndexRoute: SidebarRunsIndexRoute,
}

const SidebarRunsRouteWithChildren = SidebarRunsRoute._addFileChildren(
  SidebarRunsRouteChildren,
)

interface SidebarRouteRouteChildren {
  SidebarConfigRoute: typeof SidebarConfigRoute
  SidebarProfileRoute: typeof SidebarProfileRoute
  SidebarRunsRoute: typeof SidebarRunsRouteWithChildren
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarConfigRoute: SidebarConfigRoute,
  SidebarProfileRoute: SidebarProfileRoute,
  SidebarRunsRoute: SidebarRunsRouteWithChildren,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
