"""Build the DQX Studio application bundle (source-shipped, uv-run model).

Produces, under ``app/.build/`` — a self-contained source tree the
Databricks Apps runtime runs via ``uv run`` (no application wheel):

* ``pyproject.toml`` / ``uv.lock`` — copied from the app root so ``uv run``
  resolves the exact locked environment (and fetches the required Python)
  inside the Apps container, regardless of the container's system Python.
* ``README.md`` — copied because ``[project].readme`` references it (hatch
  needs it when ``uv run`` installs the app package).
* ``src/databricks_labs_dqx_app/`` — the package source, including the built
  UI (``__dist__``), ``_metadata.py``, and ``_version.py``. The ``ui/``
  TypeScript source is excluded (only the compiled ``__dist__`` is needed at
  runtime).
* ``requirements.txt`` — the single line ``uv``. The Apps ``[BUILD]`` phase
  ``pip install``s this into the platform venv; ``uv`` then builds the real
  environment from ``pyproject.toml`` + ``uv.lock`` at launch — which is what
  lets the app target a newer Python than the container's system Python.
* ``_vendor/dqx/`` — the co-developed ``databricks-labs-dqx`` library source,
  vendored only while the app resolves it from a local path (see
  ``_vendor_dqx_library``). The container never sees the parent checkout, so
  the path source has to be retargeted inside the deploy tree.
* ``app.yml`` — Databricks Apps launch manifest (``uv run uvicorn`` …), a
  fallback for non-DABs deploys; DABs overrides the command via
  ``var.app_config.command`` in ``databricks.yml``.

Side effects on the source tree:

* ``src/databricks_labs_dqx_app/_metadata.py`` and ``_version.py`` are
  regenerated (from ``[tool.dqx_app.metadata]`` and ``[project].version``).
* ``src/databricks_labs_dqx_app/ui/lib/api.ts`` is regenerated by orval.
* ``src/databricks_labs_dqx_app/__dist__/`` is overwritten by ``vite build``.

The script is invoked from the ``app-build`` Makefile target (and
transitively from the ``databricks.yml`` ``artifacts.default.build``
pipeline, which additionally builds the task-runner wheel for the job).
Designed to be cwd-independent — paths resolve relative to this file.
"""

import json
import os
import re
import shutil
import subprocess
import tempfile
import tomllib
from pathlib import Path

APP_DIR = Path(__file__).resolve().parent.parent  # scripts/build_app.py → app/
PYPROJECT = APP_DIR / "pyproject.toml"
UV_LOCK = APP_DIR / "uv.lock"
README = APP_DIR / "README.md"
BUILD_DIR = APP_DIR / ".build"
NODE_BIN = APP_DIR / "node_modules" / ".bin"

DQX_DIR = APP_DIR.parent
# Mirrors ``[tool.hatch.build.targets.sdist].only-include`` in the DQX
# pyproject: the minimum hatchling needs to build the library from source.
DQX_VENDOR_FILES = ("pyproject.toml", "README.md", "LICENSE", "NOTICE")
DQX_VENDOR_REL = "_vendor/dqx"

PKG_DIR = APP_DIR / "src" / "databricks_labs_dqx_app"
METADATA_PY = PKG_DIR / "_metadata.py"
VERSION_PY = PKG_DIR / "_version.py"
API_TS = PKG_DIR / "ui" / "lib" / "api.ts"
DIST_DIR = PKG_DIR / "__dist__"
TASKS_DIR = APP_DIR / "tasks"
REPRODUCIBLE_BUILD_EPOCH = "315532800"


def _step(msg: str) -> None:
    print(f"\n▶ {msg}", flush=True)


def _run(
    cmd: list[str],
    *,
    cwd: Path = APP_DIR,
    env: dict[str, str] | None = None,
    quiet: bool = False,
) -> None:
    """Run a subprocess from ``APP_DIR`` with stdio passed through.

    Failures abort the build via ``check=True`` — every stage must
    succeed for the deploy tree to be considered usable.
    """
    if not quiet:
        print(f"  $ {' '.join(cmd)}", flush=True)
    output = subprocess.DEVNULL if quiet else None
    subprocess.run(cmd, cwd=cwd, check=True, env=env, stdout=output, stderr=output)  # noqa: S603


def _node_bin(name: str) -> str:
    """Return the path to a ``node_modules/.bin`` executable for this platform."""
    suffix = ".cmd" if os.name == "nt" else ""
    return str(NODE_BIN / f"{name}{suffix}")


def _load_pyproject() -> dict:
    with PYPROJECT.open("rb") as f:
        return tomllib.load(f)


def _read_app_metadata(pyproject: dict) -> dict[str, str]:
    """Return ``[tool.dqx_app.metadata]`` from ``pyproject.toml``.

    Single source of truth for app identity. ``vite.config.ts`` reads
    the same key — keeping the two consumers in lockstep on schema
    changes is intentional (rename here ⇒ rename there).
    """
    meta = pyproject.get("tool", {}).get("dqx_app", {}).get("metadata", {})
    required = {"app-name", "app-slug", "app-module"}
    missing = required - meta.keys()
    if missing:
        raise SystemExit(
            f"error: [tool.dqx_app.metadata] missing keys {sorted(missing)} in {PYPROJECT}",
        )
    return meta


def _write_metadata_module(meta: dict[str, str]) -> None:
    """Mirror ``[tool.dqx_app.metadata]`` into a runtime-importable module.

    ``backend.config`` and ``backend.logger`` import ``app_name`` /
    ``app_slug`` from here. Generating it on every build keeps
    source-of-truth in ``pyproject.toml`` while still letting runtime
    code do a plain ``from .._metadata import ...``.

    Uses ``json.dumps`` for value formatting because it always emits
    double-quoted strings, matching the existing file's convention and
    keeping the diff clean across repeat builds.
    """
    METADATA_PY.write_text(
        f"app_name = {json.dumps(meta['app-name'])}\n"
        f"app_module = {json.dumps(meta['app-module'])}\n"
        f"app_slug = {json.dumps(meta['app-slug'])}\n"
        'api_prefix = "/api"\n',
        encoding="utf-8",
    )


def _write_version_module(version: str) -> None:
    """Write the static ``_version.py`` imported by ``__init__``.

    Replaces the old git-based ``uv-dynamic-versioning`` build hook: the
    app ships as source with a static ``[project].version``, so the
    version is known without git (the Apps container has none).
    """
    VERSION_PY.write_text(f'version = "{version}"\n', encoding="utf-8")


def _write_app_yml(meta: dict[str, str]) -> None:
    """Write the Databricks Apps launch manifest (``uv run`` form).

    Single-worker uvicorn under ``uv run`` so the container resolves the
    locked environment (and required Python) at launch. Production DABs
    deploys override this via ``var.app_config.command`` in
    ``databricks.yml``; this manifest is the fallback for paths that don't
    go through DABs (e.g. direct ``databricks apps`` CLI deploys).
    """
    (BUILD_DIR / "app.yml").write_text(
        f'command: ["uv", "run", "--no-dev", "uvicorn", "{meta["app-module"]}", "--workers", "1"]\n',
        encoding="utf-8",
    )


def _dump_openapi() -> None:
    """Import the FastAPI app and serialize its OpenAPI schema.

    Runs in a subprocess via ``uv run`` so the schema is dumped with
    exactly the same environment the app uses — same pydantic / fastapi
    versions, same plugin set.
    """
    _run(openapi_dump_command(BUILD_DIR / "openapi.json"))


def openapi_dump_command(target: Path) -> list[str]:
    """Return the frozen command used to generate an OpenAPI document.

    Args:
        target: Destination path for the generated JSON document.

    Returns:
        The uv command and Python snippet used by the application build.
    """
    code = (
        "import json, sys;"
        "from databricks_labs_dqx_app.backend.app import app;"
        f"open({str(target)!r}, 'w').write(json.dumps(app.openapi(), indent=2))"
    )
    return ["uv", "run", "--frozen", "--exact", "--all-extras", "python", "-c", code]


def _run_orval() -> None:
    """Regenerate ``ui/lib/api.ts`` from ``.build/openapi.json``.

    Config picked up from ``orval.config.ts`` at app root. Invokes the
    locally-installed binary directly so the pinned ``orval`` is used
    regardless of which package manager is on PATH.
    """
    _run([_node_bin("orval")])


def _run_vite_build() -> None:
    """Compile the React UI into ``src/databricks_labs_dqx_app/__dist__/``.

    Vite reads ``vite.config.ts``, which sets ``build.outDir`` to the
    package's ``__dist__`` folder so it ships inside the package source.
    """
    _run([_node_bin("vite"), "build"])


def _assemble_deploy_tree() -> None:
    """Assemble the source tree the Apps runtime runs via ``uv run``.

    Copies the app root's ``pyproject.toml`` / ``uv.lock`` / ``README.md``
    and the package ``src/`` (minus the ``ui/`` TS source and caches) into
    ``.build/``, and writes ``requirements.txt`` = ``uv``. ``.build/tasks``
    (the task-runner wheel, built by the ``databricks.yml`` pipeline after
    this script) is left untouched.
    """
    # Sweep stale wheels from the previous (wheel-based) layout so they
    # don't linger in the synced source tree.
    for stale in list(BUILD_DIR.glob("*.whl")):
        stale.unlink()
    shutil.rmtree(BUILD_DIR / "wheels", ignore_errors=True)

    shutil.copy2(PYPROJECT, BUILD_DIR / "pyproject.toml")
    shutil.copy2(UV_LOCK, BUILD_DIR / "uv.lock")
    shutil.copy2(README, BUILD_DIR / "README.md")

    dest_pkg = BUILD_DIR / "src" / "databricks_labs_dqx_app"
    shutil.rmtree(BUILD_DIR / "src", ignore_errors=True)
    shutil.copytree(
        PKG_DIR,
        dest_pkg,
        ignore=shutil.ignore_patterns("ui", "__pycache__", "*.pyc"),
    )

    (BUILD_DIR / "requirements.txt").write_text("uv\n", encoding="utf-8")


def _local_dqx_path(pyproject: dict) -> str | None:
    """Return the local path ``databricks-labs-dqx`` resolves from, if any.

    Returns ``None`` once the app pins the published wheel instead — at which
    point nothing needs vendoring and the deploy tree is used verbatim.
    """
    sources = pyproject.get("tool", {}).get("uv", {}).get("sources", {})
    path = sources.get("databricks-labs-dqx", {}).get("path")
    return path if isinstance(path, str) else None


def _vendor_dqx_library() -> None:
    """Copy the co-developed DQX library into ``.build/_vendor/dqx/``.

    The Apps container only ever receives the app directory, so a path source
    pointing outside it (``../``) cannot resolve there — ``uv run`` fails at
    launch trying to read metadata from a directory that was never uploaded.
    Copying ``src/`` plus the metadata files hatchling reads makes the library
    resolvable in-tree. The library's version comes from
    ``src/databricks/labs/dqx/__about__.py``, so the build needs no git.
    """
    dest = BUILD_DIR / DQX_VENDOR_REL
    shutil.rmtree(dest, ignore_errors=True)
    dest.mkdir(parents=True)

    for name in DQX_VENDOR_FILES:
        shutil.copy2(DQX_DIR / name, dest / name)

    shutil.copytree(
        DQX_DIR / "src",
        dest / "src",
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
    )


def _retarget_dqx_source(local_path: str) -> None:
    """Point the deploy tree's path source at the vendored copy.

    Rewrites the *copied* ``pyproject.toml`` and ``uv.lock``, never the
    tracked originals. A plain string swap keeps the deployed lock otherwise
    byte-identical to the committed one, so the container installs exactly the
    resolution that was tested — re-locking here would instead risk dependency
    drift and bake the build machine's registry URLs into the deploy.
    """
    for target, key in ((BUILD_DIR / "pyproject.toml", "path"), (BUILD_DIR / "uv.lock", "directory")):
        text = target.read_text(encoding="utf-8")
        needle = f'{key} = "{local_path}"'
        if needle not in text:
            raise SystemExit(f"error: expected {needle!r} in {target} — cannot retarget the local dqx source")
        target.write_text(text.replace(needle, f'{key} = "{DQX_VENDOR_REL}"'), encoding="utf-8")


def build_task_runner_wheel(output_dir: Path, dqx_version: str) -> Path:
    """Build a reproducible task-runner wheel pinned to the released DQX version.

    The regular bundle build keeps resolving the runner's DQX dependency through
    the bundle environment. Marketplace has no sibling checkout or bundle
    variable, so its wheel metadata must carry the same exact release pin as the
    application. The tracked task-runner project is never modified.

    Args:
        output_dir: Directory that will contain the single built wheel.
        dqx_version: Published DQX version required by the wheel.

    Returns:
        Path to the built task-runner wheel.
    """
    if re.fullmatch(r"[0-9]+\.[0-9]+\.[0-9]+(?:[A-Za-z0-9.-]*)", dqx_version) is None:
        raise ValueError("dqx_version must be a release version")

    shutil.rmtree(output_dir, ignore_errors=True)
    output_dir.mkdir(parents=True)
    with tempfile.TemporaryDirectory(prefix=".marketplace-task-", dir=output_dir.parent) as temp_dir:
        task_source = Path(temp_dir) / "tasks"
        shutil.copytree(
            TASKS_DIR,
            task_source,
            ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "uv.lock"),
        )
        task_pyproject = task_source / "pyproject.toml"
        task_text = task_pyproject.read_text(encoding="utf-8")
        task_text, replacements = re.subn(
            r'(?m)^(\s*)"databricks-labs-dqx",$',
            rf'\1"databricks-labs-dqx=={dqx_version}",',
            task_text,
        )
        if replacements != 1:
            raise RuntimeError("Task-runner DQX dependency declaration changed")
        task_pyproject.write_text(task_text.replace("\r\n", "\n"), encoding="utf-8", newline="\n")

        build_env = os.environ.copy()
        build_env["SOURCE_DATE_EPOCH"] = REPRODUCIBLE_BUILD_EPOCH
        build_env["PYTHONHASHSEED"] = "0"
        build_env["UV_BUILD_CONSTRAINT"] = str(DQX_DIR / ".build-constraints.txt")
        for name in ("UV_INDEX", "UV_EXTRA_INDEX_URL", "UV_INDEX_URL", "PIP_INDEX_URL", "PIP_EXTRA_INDEX_URL"):
            build_env.pop(name, None)
        try:
            _run(
                ["uv", "build", ".", "--wheel", "--out-dir", str(output_dir)],
                cwd=task_source,
                env=build_env,
                quiet=True,
            )
        except subprocess.CalledProcessError as error:
            raise RuntimeError("Task-runner wheel build failed") from error

    wheels = sorted(output_dir.glob("databricks_labs_dqx_task_runner-*.whl"))
    if len(wheels) != 1:
        raise RuntimeError("Task-runner build did not produce exactly one wheel")
    (output_dir / ".gitignore").unlink(missing_ok=True)
    return wheels[0]


def main() -> int:
    BUILD_DIR.mkdir(parents=True, exist_ok=True)

    pyproject = _load_pyproject()
    meta = _read_app_metadata(pyproject)
    version = pyproject["project"]["version"]

    _step("Writing _metadata.py from pyproject [tool.dqx_app.metadata]")
    _write_metadata_module(meta)

    _step(f"Writing _version.py (version={version})")
    _write_version_module(version)

    _step("Writing .build/app.yml")
    _write_app_yml(meta)

    _step("Dumping FastAPI OpenAPI schema → .build/openapi.json")
    _dump_openapi()

    _step("Generating UI API client (orval)")
    _run_orval()

    _step("Building UI bundle (vite build → src/databricks_labs_dqx_app/__dist__/)")
    _run_vite_build()

    _step("Assembling .build/ source tree (pyproject + uv.lock + src + requirements.txt=uv)")
    _assemble_deploy_tree()

    local_dqx = _local_dqx_path(pyproject)
    if local_dqx:
        _step(f"Vendoring local databricks-labs-dqx ({local_dqx} → {DQX_VENDOR_REL})")
        _vendor_dqx_library()
        _retarget_dqx_source(local_dqx)

    _step("Build complete:")
    print(f"  → {(BUILD_DIR / 'src' / 'databricks_labs_dqx_app').relative_to(APP_DIR)} (source), requirements.txt=uv")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
