"""Build the DQX Studio application bundle (source-shipped, uv-run model).

Produces, under ``app/.build/`` — a self-contained source tree the
Databricks Apps runtime runs via ``uv run`` (no application wheel):

* ``pyproject.toml`` / ``uv.lock`` — copied from the app root so ``uv run``
  resolves the exact locked environment (and fetches the required Python)
  inside the Apps container, regardless of the container's system Python.
* ``README.md`` — copied because ``[project].readme`` references it (hatch
  needs it when ``uv run`` installs the app package).
* ``src/databricks_labs_dqx_app/`` — the package source, including the built
  UI (``__dist__``), ``_metadata.py``, and ``_version.py``. The ``ui/``
  TypeScript source is excluded (only the compiled ``__dist__`` is needed at
  runtime).
* ``requirements.txt`` — the single line ``uv``. The Apps ``[BUILD]`` phase
  ``pip install``s this into the platform venv; ``uv`` then builds the real
  environment from ``pyproject.toml`` + ``uv.lock`` at launch — which is what
  lets the app target a newer Python than the container's system Python.
* ``app.yml`` — Databricks Apps launch manifest (``uv run uvicorn`` …), a
  fallback for non-DABs deploys; DABs overrides the command via
  ``var.app_config.command`` in ``databricks.yml``.

Side effects on the source tree:

* ``src/databricks_labs_dqx_app/_metadata.py`` and ``_version.py`` are
  regenerated (from ``[tool.dqx_app.metadata]`` and ``[project].version``).
* ``src/databricks_labs_dqx_app/ui/lib/api.ts`` is regenerated by orval.
* ``src/databricks_labs_dqx_app/__dist__/`` is overwritten by ``vite build``.

The script is invoked from the ``app-build`` Makefile target (and
transitively from the ``databricks.yml`` ``artifacts.default.build``
pipeline, which additionally builds the task-runner wheel for the job).
Designed to be cwd-independent — paths resolve relative to this file.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import tomllib
from pathlib import Path

APP_DIR = Path(__file__).resolve().parent.parent  # scripts/build_app.py → app/
PYPROJECT = APP_DIR / "pyproject.toml"
UV_LOCK = APP_DIR / "uv.lock"
README = APP_DIR / "README.md"
BUILD_DIR = APP_DIR / ".build"
NODE_BIN = APP_DIR / "node_modules" / ".bin"

PKG_DIR = APP_DIR / "src" / "databricks_labs_dqx_app"
METADATA_PY = PKG_DIR / "_metadata.py"
VERSION_PY = PKG_DIR / "_version.py"
API_TS = PKG_DIR / "ui" / "lib" / "api.ts"
DIST_DIR = PKG_DIR / "__dist__"


def _step(msg: str) -> None:
    print(f"\n▶ {msg}", flush=True)


def _run(cmd: list[str]) -> None:
    """Run a subprocess from ``APP_DIR`` with stdio passed through.

    Failures abort the build via ``check=True`` — every stage must
    succeed for the deploy tree to be considered usable.
    """
    print(f"  $ {' '.join(cmd)}", flush=True)
    subprocess.run(cmd, cwd=APP_DIR, check=True)  # noqa: S603


def _load_pyproject() -> dict:
    with PYPROJECT.open("rb") as f:
        return tomllib.load(f)


def _read_app_metadata(pyproject: dict) -> dict[str, str]:
    """Return ``[tool.dqx_app.metadata]`` from ``pyproject.toml``.

    Single source of truth for app identity. ``vite.config.ts`` reads
    the same key — keeping the two consumers in lockstep on schema
    changes is intentional (rename here ⇒ rename there).
    """
    meta = pyproject.get("tool", {}).get("dqx_app", {}).get("metadata", {})
    required = {"app-name", "app-slug", "app-module"}
    missing = required - meta.keys()
    if missing:
        raise SystemExit(
            f"error: [tool.dqx_app.metadata] missing keys {sorted(missing)} in {PYPROJECT}",
        )
    return meta


def _write_metadata_module(meta: dict[str, str]) -> None:
    """Mirror ``[tool.dqx_app.metadata]`` into a runtime-importable module.

    ``backend.config`` and ``backend.logger`` import ``app_name`` /
    ``app_slug`` from here. Generating it on every build keeps
    source-of-truth in ``pyproject.toml`` while still letting runtime
    code do a plain ``from .._metadata import ...``.

    Uses ``json.dumps`` for value formatting because it always emits
    double-quoted strings, matching the existing file's convention and
    keeping the diff clean across repeat builds.
    """
    METADATA_PY.write_text(
        f"app_name = {json.dumps(meta['app-name'])}\n"
        f"app_module = {json.dumps(meta['app-module'])}\n"
        f"app_slug = {json.dumps(meta['app-slug'])}\n"
        'api_prefix = "/api"\n',
        encoding="utf-8",
    )


def _write_version_module(version: str) -> None:
    """Write the static ``_version.py`` imported by ``__init__``.

    Replaces the old git-based ``uv-dynamic-versioning`` build hook: the
    app ships as source with a static ``[project].version``, so the
    version is known without git (the Apps container has none).
    """
    VERSION_PY.write_text(f'version = "{version}"\n', encoding="utf-8")


def _write_app_yml(meta: dict[str, str]) -> None:
    """Write the Databricks Apps launch manifest (``uv run`` form).

    Single-worker uvicorn under ``uv run`` so the container resolves the
    locked environment (and required Python) at launch. Production DABs
    deploys override this via ``var.app_config.command`` in
    ``databricks.yml``; this manifest is the fallback for paths that don't
    go through DABs (e.g. direct ``databricks apps`` CLI deploys).
    """
    (BUILD_DIR / "app.yml").write_text(
        f'command: ["uv", "run", "--no-dev", "uvicorn", "{meta["app-module"]}", "--workers", "1"]\n',
        encoding="utf-8",
    )


def _dump_openapi() -> None:
    """Import the FastAPI app and serialize its OpenAPI schema.

    Runs in a subprocess via ``uv run`` so the schema is dumped with
    exactly the same environment the app uses — same pydantic / fastapi
    versions, same plugin set.
    """
    target = BUILD_DIR / "openapi.json"
    code = (
        "import json, sys;"
        "from databricks_labs_dqx_app.backend.app import app;"
        f"open({str(target)!r}, 'w').write(json.dumps(app.openapi(), indent=2))"
    )
    _run(["uv", "run", "--exact", "--all-extras", "python", "-c", code])


def _run_orval() -> None:
    """Regenerate ``ui/lib/api.ts`` from ``.build/openapi.json``.

    Config picked up from ``orval.config.ts`` at app root. Invokes the
    locally-installed binary directly so the pinned ``orval`` is used
    regardless of which package manager is on PATH.
    """
    _run([str(NODE_BIN / "orval")])


def _run_vite_build() -> None:
    """Compile the React UI into ``src/databricks_labs_dqx_app/__dist__/``.

    Vite reads ``vite.config.ts``, which sets ``build.outDir`` to the
    package's ``__dist__`` folder so it ships inside the package source.
    """
    _run([str(NODE_BIN / "vite"), "build"])


def _assemble_deploy_tree() -> None:
    """Assemble the source tree the Apps runtime runs via ``uv run``.

    Copies the app root's ``pyproject.toml`` / ``uv.lock`` / ``README.md``
    and the package ``src/`` (minus the ``ui/`` TS source and caches) into
    ``.build/``, and writes ``requirements.txt`` = ``uv``. ``.build/tasks``
    (the task-runner wheel, built by the ``databricks.yml`` pipeline after
    this script) is left untouched.
    """
    # Sweep stale wheels from the previous (wheel-based) layout so they
    # don't linger in the synced source tree.
    for stale in list(BUILD_DIR.glob("*.whl")):
        stale.unlink()

    shutil.copy2(PYPROJECT, BUILD_DIR / "pyproject.toml")
    shutil.copy2(UV_LOCK, BUILD_DIR / "uv.lock")
    shutil.copy2(README, BUILD_DIR / "README.md")

    dest_pkg = BUILD_DIR / "src" / "databricks_labs_dqx_app"
    shutil.rmtree(BUILD_DIR / "src", ignore_errors=True)
    shutil.copytree(
        PKG_DIR,
        dest_pkg,
        ignore=shutil.ignore_patterns("ui", "__pycache__", "*.pyc"),
    )

    (BUILD_DIR / "requirements.txt").write_text("uv\n", encoding="utf-8")


def main() -> int:
    BUILD_DIR.mkdir(parents=True, exist_ok=True)

    pyproject = _load_pyproject()
    meta = _read_app_metadata(pyproject)
    version = pyproject["project"]["version"]

    _step("Writing _metadata.py from pyproject [tool.dqx_app.metadata]")
    _write_metadata_module(meta)

    _step(f"Writing _version.py (version={version})")
    _write_version_module(version)

    _step("Writing .build/app.yml")
    _write_app_yml(meta)

    _step("Dumping FastAPI OpenAPI schema → .build/openapi.json")
    _dump_openapi()

    _step("Generating UI API client (orval)")
    _run_orval()

    _step("Building UI bundle (vite build → src/databricks_labs_dqx_app/__dist__/)")
    _run_vite_build()

    _step("Assembling .build/ source tree (pyproject + uv.lock + src + requirements.txt=uv)")
    _assemble_deploy_tree()

    _step("Build complete:")
    print(f"  → {(BUILD_DIR / 'src' / 'databricks_labs_dqx_app').relative_to(APP_DIR)} (source), requirements.txt=uv")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
