- name: "product_code_not_null_with_high_null_count"
  business_description: "Product catalog database tracking all products in inventory with product codes and names"
  data_summary_stats:
    product_code:
      mean: null
      min: "PRD001"
      max: "PRD950"
    product_name:
      mean: null
      min: "Product A"
      max: "Product Z"
  quality_rules: '[{"criticality":"error","check":{"function":"is_not_null","arguments":{"column":"product_code"}}}]'
  reasoning: "Product code is a critical identifier field that should not have nulls to maintain referential integrity."

- name: "order_quantity_reasonable_range_from_stats"
  data_summary_stats:
    quantity:
      mean: "50.5"
      min: "1"
      max: "100"
    order_id:
      mean: null
      min: "ORD001"
      max: "ORD1000"
  quality_rules: '[{"criticality":"error","check":{"function":"is_in_range","arguments":{"column":"quantity","min_limit":1,"max_limit":100}}}]'
  reasoning: "Based on the statistics, quantity ranges from 1 to 100 with a mean of 50.5, which represents the normal business range for order quantities."

- name: "price_positive_and_within_observed_range"
  business_description: "E-commerce pricing data for products sold online, ensuring all prices are valid and within acceptable ranges"
  data_summary_stats:
    price:
      mean: "125.50"
      min: "10.00"
      max: "500.00"
    product_id:
      mean: null
      min: "P001"
      max: "P999"
  quality_rules: '[{"criticality":"error","check":{"function":"is_in_range","arguments":{"column":"price","min_limit":10.00,"max_limit":500.00}}}]'
  reasoning: "Price statistics show the data ranges from $10 to $500 with a mean of $125.50. This range should be enforced to catch data entry errors."

- name: "age_within_valid_range_based_on_distribution"
  data_summary_stats:
    age:
      mean: "42.5"
      min: "18"
      max: "75"
    customer_id:
      mean: null
      min: "C001"
      max: "C1000"
  quality_rules: '[{"criticality":"error","check":{"function":"is_in_range","arguments":{"column":"age","min_limit":18,"max_limit":75}}}]'
  reasoning: "Age distribution shows values between 18 and 75 with mean 42.5, which is the expected range for adult customers."

- name: "temperature_sensor_range_validation"
  business_description: "IoT sensor data from manufacturing facility monitoring ambient temperature across different zones"
  data_summary_stats:
    temperature:
      mean: "22.5"
      min: "-10.0"
      max: "50.0"
    sensor_id:
      mean: null
      min: "SEN001"
      max: "SEN100"
    timestamp:
      mean: null
      min: "2024-01-01 00:00:00"
      max: "2024-12-31 23:59:59"
  quality_rules: '[{"criticality":"warn","check":{"function":"is_in_range","arguments":{"column":"temperature","min_limit":-10.0,"max_limit":50.0}}}]'
  reasoning: "Temperature sensor data shows a range from -10°C to 50°C with mean 22.5°C. Values outside this range may indicate sensor malfunction."

- name: "order_amount_positive_no_nulls"
  data_summary_stats:
    order_amount:
      mean: "250.75"
      min: "0.01"
      max: "2500.00"
    order_date:
      mean: null
      min: "2024-01-01"
      max: "2024-12-31"
  quality_rules: '[{"criticality":"error","check":{"function":"is_not_null","arguments":{"column":"order_amount"}}},{"criticality":"error","check":{"function":"is_in_range","arguments":{"column":"order_amount","min_limit":0.01,"max_limit":2500.00}}}]'
  reasoning: "Order amount ranges from $0.01 to $2500 with mean $250.75. All orders must have an amount and be within the valid business range."

- name: "discount_percentage_reasonable_range"
  business_description: "Promotional discount tracking system for retail products across different categories"
  data_summary_stats:
    discount_percentage:
      mean: "15.5"
      min: "0.0"
      max: "50.0"
    product_category:
      mean: null
      min: "Category A"
      max: "Category Z"
  quality_rules: '[{"criticality":"error","check":{"function":"is_in_range","arguments":{"column":"discount_percentage","min_limit":0.0,"max_limit":50.0}}}]'
  reasoning: "Discount percentage ranges from 0% to 50% with a mean of 15.5%. This is the acceptable business range for discounts."

- name: "rating_bounded_integer_range"
  data_summary_stats:
    rating:
      mean: "3.8"
      min: "1"
      max: "5"
    product_id:
      mean: null
      min: "P0001"
      max: "P9999"
    review_date:
      mean: null
      min: "2024-01-01"
      max: "2024-12-31"
  quality_rules: '[{"criticality":"error","check":{"function":"is_in_range","arguments":{"column":"rating","min_limit":1,"max_limit":5}}}]'
  reasoning: "Rating statistics show values strictly between 1 and 5 with mean 3.8, which is the valid range for star ratings."

- name: "employee_id_no_nulls_high_coverage"
  business_description: "Human resources employee database with employee information and department assignments"
  data_summary_stats:
    employee_id:
      mean: null
      min: "E001"
      max: "E1000"
    department:
      mean: null
      min: "Engineering"
      max: "Sales"
  quality_rules: '[{"criticality":"error","check":{"function":"is_not_null","arguments":{"column":"employee_id"}}}]'
  reasoning: "Employee ID is a required identifier field that must be present for all records to maintain data integrity."

- name: "transaction_amount_outlier_detection"
  data_summary_stats:
    transaction_amount:
      mean: "500.00"
      min: "1.00"
      max: "5000.00"
    transaction_type:
      mean: null
      min: "credit"
      max: "debit"
  quality_rules: '[{"criticality":"warn","check":{"function":"is_in_range","arguments":{"column":"transaction_amount","min_limit":1.00,"max_limit":5000.00}}}]'
  reasoning: "Transaction amounts range from $1 to $5000 with mean $500. Using the observed range helps detect outliers and data entry errors."

- name: "timestamp_freshness_based_on_max"
  business_description: "Real-time event tracking system for user interactions on website and mobile app"
  data_summary_stats:
    event_timestamp:
      mean: null
      min: "2024-12-30 00:00:00"
      max: "2024-12-31 23:59:59"
    event_type:
      mean: null
      min: "click"
      max: "view"
  quality_rules: '[{"criticality":"error","check":{"function":"is_data_fresh","arguments":{"column":"event_timestamp","max_age_minutes":1440}}}]'
  reasoning: "Event timestamps show data from the last 2 days (min: 2024-12-30, max: 2024-12-31). Events should be within 24 hours to be considered fresh."

- name: "percentage_field_bounded_range"
  data_summary_stats:
    completion_percentage:
      mean: "67.5"
      min: "0.0"
      max: "100.0"
    task_id:
      mean: null
      min: "T001"
      max: "T1500"
  quality_rules: '[{"criticality":"error","check":{"function":"is_in_range","arguments":{"column":"completion_percentage","min_limit":0.0,"max_limit":100.0}}}]'
  reasoning: "Completion percentage naturally ranges from 0 to 100 with mean 67.5%, representing the valid range for percentage fields."

- name: "salary_reasonable_business_range"
  business_description: "Payroll system tracking employee compensation across different job levels and departments"
  data_summary_stats:
    salary:
      mean: "75000.00"
      min: "30000.00"
      max: "200000.00"
    job_level:
      mean: null
      min: "Junior"
      max: "Senior"
  quality_rules: '[{"criticality":"warn","check":{"function":"is_in_range","arguments":{"column":"salary","min_limit":30000.00,"max_limit":200000.00}}}]'
  reasoning: "Salary ranges from $30K to $200K with mean $75K. This represents the company's typical salary range and should be validated."

- name: "stock_quantity_non_negative"
  data_summary_stats:
    stock_quantity:
      mean: "125.5"
      min: "0"
      max: "1000"
    product_sku:
      mean: null
      min: "SKU001"
      max: "SKU2500"
  quality_rules: '[{"criticality":"error","check":{"function":"is_in_range","arguments":{"column":"stock_quantity","min_limit":0,"max_limit":1000}}}]'
  reasoning: "Stock quantity ranges from 0 to 1000 units with mean 125.5. The minimum of 0 indicates out-of-stock items are valid, but negative values would be errors."

- name: "email_completeness_check"
  business_description: "User registration database storing customer account information including contact details"
  data_summary_stats:
    email:
      mean: null
      min: "alice@example.com"
      max: "zoe@example.com"
    username:
      mean: null
      min: "alice"
      max: "zoe"
  quality_rules: '[{"criticality":"warn","check":{"function":"is_not_null_and_not_empty","arguments":{"column":"email"}}}]'
  reasoning: "Email should be present for all user accounts to enable communication. Missing emails should be flagged as warnings for follow-up."
