name: anomaly

on:
  pull_request:
    types: [ opened, synchronize, ready_for_review ]
  merge_group:
    types: [ checks_requested ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false  # don't cancel ongoing runs to ensure fixtures are completed and resources terminated

jobs:
  # Only run jobs for PRs from branches on the main repository and not from forks.
  # Workflows triggered by PRs from forks don't have access to the tool environment.
  # PRs from forks to be tested by the reviewer(s) / maintainer(s) before merging.

  anomaly-tests:
    if: github.event_name == 'pull_request' && !github.event.pull_request.draft && !github.event.pull_request.head.repo.fork
    environment: tool
    runs-on:
      group: larger-runners
      labels: larger
    permissions:
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env

      # Create .coveragerc with correct relative path to source code.
      - name: Prepare code coverage configuration for anomaly tests
        run: |
          cat > tests/integration_anomaly/.coveragerc << EOF
          [run]
          source = ../../src
          relative_files = true
          parallel = true
          EOF

      - name: Run anomaly integration tests
        uses: databrickslabs/sandbox/acceptance@3313d06ce86227537b3f37f5974f7eecb2a8e59a # acceptance/v0.4.4
        with:
          vault_uri: ${{ secrets.VAULT_URI }}
          timeout: 3h
          codegen_path: tests/integration_anomaly/.codegen.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          COVERAGE_FILE: ${{ github.workspace }}/.coverage
          MLFLOW_ENABLE_DB_SDK: "true"
          MLFLOW_TRACKING_URI: databricks
          MLFLOW_REGISTRY_URI: databricks-uc
          MLFLOW_HTTP_REQUEST_TIMEOUT: "600"
          MLFLOW_HTTP_REQUEST_MAX_RETRIES: "10"

      - name: Merge coverage reports and convert them to XML
        run: make combine-coverage

      # Recursively search the entire workspace directory for all coverage reports.
      # All uploaded test coverage reports will be used even if publish is done multiple time.
      - name: Publish test coverage
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        with:
          use_oidc: true

  anomaly-tests-serverless:
    if: github.event_name == 'pull_request' && !github.event.pull_request.draft && !github.event.pull_request.head.repo.fork
    environment: tool
    runs-on:
      group: larger-runners
      labels: larger
    permissions:
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env

      # Create .coveragerc with correct relative path to source code.
      - name: Prepare code coverage configuration for anomaly tests
        run: |
          cat > tests/integration_anomaly/.coveragerc << EOF
          [run]
          source = ../../src
          relative_files = true
          parallel = true
          EOF

      - name: Run anomaly integration tests on serverless cluster
        uses: databrickslabs/sandbox/acceptance@3313d06ce86227537b3f37f5974f7eecb2a8e59a # acceptance/v0.4.4
        with:
          vault_uri: ${{ secrets.VAULT_URI }}
          timeout: 3h
          codegen_path: tests/integration_anomaly/.codegen.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          COVERAGE_FILE: ${{ github.workspace }}/.coverage
          DATABRICKS_SERVERLESS_COMPUTE_ID: auto
          MLFLOW_ENABLE_DB_SDK: "true"
          MLFLOW_TRACKING_URI: databricks
          MLFLOW_REGISTRY_URI: databricks-uc
          MLFLOW_HTTP_REQUEST_TIMEOUT: "600"
          MLFLOW_HTTP_REQUEST_MAX_RETRIES: "10"

      - name: Merge coverage reports and convert them to XML
        run: make combine-coverage

      # collects all coverage reports
      - name: Publish test coverage
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        with:
          use_oidc: true
