name: auth_test

on:
  pull_request:
    types: [ opened, synchronize, ready_for_review ]
  merge_group:
    types: [ checks_requested ]
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  auth_test:
    if: github.event_name == 'pull_request'
    environment: tool
    runs-on: larger
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks --version

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Set env vars for Azure CLI auth
        run: |
          host=$(az keyvault secret show --id "${{ secrets.VAULT_URI }}/secrets/DATABRICKS-HOST" --query value -o tsv)
          [[ $host != http* ]] && host="https://$host"
          echo "DATABRICKS_HOST=$val" >> $GITHUB_ENV
          echo "DATABRICKS_AUTH_TYPE=azure-cli" >> $GITHUB_ENV
#
#      - name: List Databricks clusters
#        run: databricks clusters list | cat

      - name: Install dbt-databricks
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-databricks

      - name: Set env vars for dbt auth (azure-cli auth)
        run: |
          http_path=$(az keyvault secret show --id "${{ secrets.VAULT_URI }}/secrets/TEST-DEFAULT-WAREHOUSE-HTTP-PATH" --query value -o tsv)
          echo "DBT_HOST=$DATABRICKS_HOST" >> $GITHUB_ENV
          echo "DBT_HTTP_PATH=$http_path" >> $GITHUB_ENV
          echo "DBT_CATALOG='main'" >> $GITHUB_ENV
          echo "DBT_SCHEMA='default'" >> $GITHUB_ENV

      - name: Create dbt profiles.yml (azure-cli auth)
        run: |
          mkdir -p $RUNNER_TEMP/dbt
          cat > $RUNNER_TEMP/dbt/profiles.yml <<'YAML'
          dbt_demo:
            target: ci
            outputs:
              ci:
                type: databricks
                host: "{{ env_var('DBT_HOST') }}"
                http_path: "{{ env_var('DBT_HTTP_PATH') }}"
                auth_type: azure-cli
                catalog: "{{ env_var('DBT_CATALOG') }}"
                schema: "{{ env_var('DBT_SCHEMA') }}"
                threads: 8
                connect_timeout: 30
          YAML
          echo "DBT_PROFILES_DIR=$RUNNER_TEMP/dbt" >> $GITHUB_ENV

#      - name: dbt debug
#        run: dbt debug --project-dir demos/dqx_demo_dbt --profiles-dir "$DBT_PROFILES_DIR"
      - name: dbt ls
        run: dbt ls --project-dir demos/dqx_demo_dbt --profiles-dir "$DBT_PROFILES_DIR"
      - name: dbt run
        run: dbt run --project-dir demos/dqx_demo_dbt --profiles-dir "$DBT_PROFILES_DIR"