name: Docs Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Must match semantic version tags like 'v1.2.3'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    name: Build Docusaurus
    runs-on:
      group: databrickslabs-protected-runner-group
      labels: linux-ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'
          python-version: '3.12'

      - name: Install Hatch
        run: |
          # click 8.3+ introduced bug for hatch
          pip install "hatch==1.13.0" "click<8.3"

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: docs/dqx/yarn.lock # need to put the lockfile path explicitly

      - name: Install dependencies
        run: make docs-install

      - name: Build website
        run: make docs-build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/dqx/build  # The directory to upload as an artifact

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    defaults:
      run:
        working-directory: docs/dqx

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on:
      group: databrickslabs-protected-runner-group
      labels: linux-ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4