name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Must match semantic version tags like 'v1.2.3'

jobs:
  publish:
    runs-on:
      group: databrickslabs-protected-runner-group
      labels: linux-ubuntu-latest
    environment: release
    permissions:
      # Used to authenticate to PyPI via OIDC and sign the release's artifacts with sigstore-python.
      id-token: write
      # Used to attach signing artifacts to the published release.
      contents: write
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-python@v5
        with:
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'
          python-version: '3.12'
      
      - name: Build wheels
        run: |
          # click 8.3+ introduced bug for hatch
          pip install "hatch==1.13.0" "click<8.3"
          hatch build
      
      - name: Github release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/databricks_*.whl
            dist/databricks_*.tar.gz

      - uses: pypa/gh-action-pypi-publish@release/v1
        name: Publish package distributions to PyPI
      
      - name: Sign artifacts with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: |
            dist/databricks_*.whl
            dist/databricks_*.tar.gz
          release-signing-artifacts: true