import logging
from typing import Any
from pyspark.sql import DataFrame, SparkSession
import yaml
from databricks.labs.blueprint.installation import Installation
from databricks.labs.dqx.base import DQEngineBase, DQEngineCoreBase
from databricks.labs.dqx.engine_core import DQEngineCore
from databricks.labs.dqx.config import WorkspaceConfig, RunConfig, InputConfig, OutputConfig
from databricks.labs.dqx.rule import (
    ChecksValidationStatus,
    ExtraParams,
    DQRule,
)
from databricks.labs.dqx.checks_handlers import (
    ChecksHandler,
    DeltaTableChecksHandler,
    WorkspaceFileChecksHandler,
    UCVolumeChecksHandler,
)
from databricks.labs.dqx.utils import deserialize_dicts, read_input_data, save_dataframe_as_table
from databricks.sdk.errors import NotFound
from databricks.sdk import WorkspaceClient

logger = logging.getLogger(__name__)
COLLECT_LIMIT_WARNING = 500


class DQEngine(DQEngineBase):
    """Data Quality Engine class to apply data quality checks to a given dataframe."""

    def __init__(
        self,
        workspace_client: WorkspaceClient,
        spark: SparkSession | None = None,
        engine: DQEngineCoreBase | None = None,
        extra_params: ExtraParams | None = None,
        _checks_handlers: dict[str, ChecksHandler] | None = None,
    ):
        super().__init__(workspace_client)

        self.spark = SparkSession.builder.getOrCreate() if spark is None else spark
        self._engine = engine or DQEngineCore(workspace_client, spark, extra_params)
        self._checks_handlers = _checks_handlers or {
            "detla_table": DeltaTableChecksHandler(self.spark, getattr(self, "ws", None)),
            "workspace_file": WorkspaceFileChecksHandler(self.spark, getattr(self, "ws", None)),
            "uc_volume": UCVolumeChecksHandler(self.spark, getattr(self, "ws", None)),
        }

    def apply_checks(
        self, df: DataFrame, checks: list[DQRule], ref_dfs: dict[str, DataFrame] | None = None
    ) -> DataFrame:
        """Applies data quality checks to a given dataframe.

        :param df: dataframe to check
        :param checks: list of checks to apply to the dataframe. Each check is an instance of DQRule class.
        :param ref_dfs: reference dataframes to use in the checks, if applicable
        :return: dataframe with errors and warning result columns
        """
        return self._engine.apply_checks(df, checks, ref_dfs)

    def apply_checks_and_split(
        self, df: DataFrame, checks: list[DQRule], ref_dfs: dict[str, DataFrame] | None = None
    ) -> tuple[DataFrame, DataFrame]:
        """Applies data quality checks to a given dataframe and split it into two ("good" and "bad"),
        according to the data quality checks.

        :param df: dataframe to check
        :param checks: list of checks to apply to the dataframe. Each check is an instance of DQRule class.
        :param ref_dfs: reference dataframes to use in the checks, if applicable
        :return: two dataframes - "good" which includes warning rows but no result columns, and "data" having
        error and warning rows and corresponding result columns
        """
        return self._engine.apply_checks_and_split(df, checks, ref_dfs)

    def apply_checks_by_metadata_and_split(
        self,
        df: DataFrame,
        checks: list[dict],
        custom_check_functions: dict[str, Any] | None = None,
        ref_dfs: dict[str, DataFrame] | None = None,
    ) -> tuple[DataFrame, DataFrame]:
        """Wrapper around `apply_checks_and_split` for use in the metadata-driven pipelines. The main difference
        is how the checks are specified - instead of using functions directly, they are described as function name plus
        arguments.

        :param df: dataframe to check
        :param checks: list of dictionaries describing checks. Each check is a dictionary consisting of following fields:
        * `check` - Column expression to evaluate. This expression should return string value if it's evaluated to true -
        it will be used as an error/warning message, or `null` if it's evaluated to `false`
        * `name` - name that will be given to a resulting column. Autogenerated if not provided
        * `criticality` (optional) - possible values are `error` (data going only into "bad" dataframe),
        and `warn` (data is going into both dataframes)
        * `filter` (optional) - Expression for filtering data quality checks
        * `user_metadata` (optional) - User-defined key-value pairs added to metadata generated by the check.
        :param custom_check_functions: dictionary with custom check functions (eg. ``globals()`` of the calling module).
        If not specified, then only built-in functions are used for the checks.
        :param ref_dfs: reference dataframes to use in the checks, if applicable
        :return: two dataframes - "good" which includes warning rows but no result columns, and "bad" having
        error and warning rows and corresponding result columns
        """
        return self._engine.apply_checks_by_metadata_and_split(df, checks, custom_check_functions, ref_dfs)

    def apply_checks_by_metadata(
        self,
        df: DataFrame,
        checks: list[dict],
        custom_check_functions: dict[str, Any] | None = None,
        ref_dfs: dict[str, DataFrame] | None = None,
    ) -> DataFrame:
        """Wrapper around `apply_checks` for use in the metadata-driven pipelines. The main difference
        is how the checks are specified - instead of using functions directly, they are described as function name plus
        arguments.

        :param df: dataframe to check
        :param checks: list of dictionaries describing checks. Each check is a dictionary consisting of following fields:
        * `check` - Column expression to evaluate. This expression should return string value if it's evaluated to true -
        it will be used as an error/warning message, or `null` if it's evaluated to `false`
        * `name` - name that will be given to a resulting column. Autogenerated if not provided
        * `criticality` (optional) - possible values are `error` (data going only into "bad" dataframe),
        and `warn` (data is going into both dataframes)
        * `filter` (optional) - Expression for filtering data quality checks
        * `user_metadata` (optional) - User-defined key-value pairs added to metadata generated by the check.
        :param custom_check_functions: dictionary with custom check functions (eg. ``globals()`` of calling module).
        :param ref_dfs: reference dataframes to use in the checks, if applicable
        If not specified, then only built-in functions are used for the checks.
        :return: dataframe with errors and warning result columns
        """
        return self._engine.apply_checks_by_metadata(df, checks, custom_check_functions, ref_dfs)

    def apply_checks_and_save_in_table(
        self,
        checks: list[DQRule],
        input_config: InputConfig,
        output_config: OutputConfig,
        quarantine_config: OutputConfig | None = None,
        ref_dfs: dict[str, DataFrame] | None = None,
    ) -> None:
        """
        Apply data quality checks to a table or view and write the result to table(s).

        If quarantine_config is provided, the data will be split into good and bad records,
        with good records written to the output table and bad records to the quarantine table.
        If quarantine_config is not provided, all records (with error/warning columns)
        will be written to the output table.

        :param checks: list of checks to apply to the dataframe. Each check is an instance of DQRule class.
        :param input_config: Input data configuration (e.g. table name or file location, read options)
        :param output_config: Output data configuration (e.g. table name, output mode, write options)
        :param quarantine_config: Optional quarantine data configuration (e.g. table name, output mode, write options)
        :param ref_dfs: Reference dataframes to use in the checks, if applicable
        """
        # Read data from the specified table
        df = read_input_data(self.spark, input_config)

        if quarantine_config:
            # Split data into good and bad records
            good_df, bad_df = self.apply_checks_and_split(df, checks, ref_dfs)
            save_dataframe_as_table(good_df, output_config)
            save_dataframe_as_table(bad_df, quarantine_config)
        else:
            # Apply checks and write all data to single table
            checked_df = self.apply_checks(df, checks, ref_dfs)
            save_dataframe_as_table(checked_df, output_config)

    def apply_checks_by_metadata_and_save_in_table(
        self,
        checks: list[dict],
        input_config: InputConfig,
        output_config: OutputConfig,
        quarantine_config: OutputConfig | None = None,
        custom_check_functions: dict[str, Any] | None = None,
        ref_dfs: dict[str, DataFrame] | None = None,
    ) -> None:
        """
        Apply data quality checks to a table or view and write the result to table(s).

        If quarantine_config is provided, the data will be split into good and bad records,
        with good records written to the output table and bad records to the quarantine table.
        If quarantine_config is not provided, all records (with error/warning columns)
        will be written to the output table.

        :param checks: List of dictionaries describing checks. Each check is a dictionary consisting of following fields:
        * `check` - Column expression to evaluate. This expression should return string value if it's evaluated to true -
        it will be used as an error/warning message, or `null` if it's evaluated to `false`
        * `name` - Name that will be given to a resulting column. Autogenerated if not provided
        * `criticality` (optional) -Possible values are `error` (data going only into "bad" dataframe),
        and `warn` (data is going into both dataframes)
        :param input_config: Input data configuration (e.g. table name or file location, read options)
        :param output_config: Output data configuration (e.g. table name, output mode, write options)
        :param quarantine_config: Optional quarantine data configuration (e.g. table name, output mode, write options)
        :param custom_check_functions: Dictionary with custom check functions (eg. ``globals()`` of calling module).
        :param ref_dfs: Reference dataframes to use in the checks, if applicable
        """
        # Read data from the specified table
        df = read_input_data(self.spark, input_config)

        if quarantine_config:
            # Split data into good and bad records
            good_df, bad_df = self.apply_checks_by_metadata_and_split(df, checks, custom_check_functions, ref_dfs)
            save_dataframe_as_table(good_df, output_config)
            save_dataframe_as_table(bad_df, quarantine_config)
        else:
            # Apply checks and write all data to single table
            checked_df = self.apply_checks_by_metadata(df, checks, custom_check_functions, ref_dfs)
            save_dataframe_as_table(checked_df, output_config)

    @staticmethod
    def validate_checks(
        checks: list[dict], custom_check_functions: dict[str, Any] | None = None
    ) -> ChecksValidationStatus:
        """
        Validate the input dict to ensure they conform to expected structure and types.

        Each check can be a dictionary. The function validates
        the presence of required keys, the existence and callability of functions, and the types
        of arguments passed to these functions.

        :param checks: List of checks to apply to the dataframe. Each check should be a dictionary.
        :param custom_check_functions: Optional dictionary with custom check functions.

        :return ValidationStatus: The validation status.
        """
        return DQEngineCore.validate_checks(checks, custom_check_functions)

    def get_invalid(self, df: DataFrame) -> DataFrame:
        """
        Get records that violate data quality checks (records with warnings and errors).
        @param df: input DataFrame.
        @return: dataframe with error and warning rows and corresponding result columns.
        """
        return self._engine.get_invalid(df)

    def get_valid(self, df: DataFrame) -> DataFrame:
        """
        Get records that don't violate data quality checks (records with warnings but no errors).
        @param df: input DataFrame.
        @return: dataframe with warning rows but no result columns.
        """
        return self._engine.get_valid(df)

    def save_results_in_table(
        self,
        output_df: DataFrame | None = None,
        quarantine_df: DataFrame | None = None,
        output_config: OutputConfig | None = None,
        quarantine_config: OutputConfig | None = None,
        run_config_name: str | None = "default",
        product_name: str = "dqx",
        assume_user: bool = True,
    ):
        """
        Save quarantine and output data to the `quarantine_table` and `output_table`.

        :param quarantine_df: Optional Dataframe containing the quarantine data
        :param output_df: Optional Dataframe containing the output data. If not provided, use run config
        :param output_config: Optional configuration for saving the output data. If not provided, use run config
        :param quarantine_config: Optional configuration for saving the quarantine data. If not provided, use run config
        :param run_config_name: Optional name of the run (config) to use
        :param product_name: name of the product/installation directory
        :param assume_user: if True, assume user installation
        """
        if output_df is not None and output_config is None:
            installation = self._get_installation(assume_user, product_name)
            run_config = self._load_run_config(installation, run_config_name)
            output_config = run_config.output_config

        if quarantine_df is not None and quarantine_config is None:
            installation = self._get_installation(assume_user, product_name)
            run_config = self._load_run_config(installation, run_config_name)
            quarantine_config = run_config.quarantine_config

        if output_df is not None and output_config is not None:
            save_dataframe_as_table(output_df, output_config)

        if quarantine_df is not None and quarantine_config is not None:
            save_dataframe_as_table(quarantine_df, quarantine_config)

    def load_checks(self, source: str, source_type: str, run_config_name: str | None = None) -> list[dict]:
        """
        Load checks from any supported backend via a registered handler.
        """
        print("load checks")
        handler = self._checks_handlers.get(source_type)
        if not handler:
            raise ValueError(f"Unknown source_type: {source_type}")
        return handler.load(source, run_config_name)

    def save_checks(
        self,
        checks: list[dict],
        target: str,
        target_type: str,
        run_config_name: str | None = None,
        mode: str | None = None,
    ) -> None:
        """
        Save checks to any supported backend via a registered handler.
        """
        handler = self._checks_handlers.get(target_type)
        if not handler:
            raise ValueError(f"Unknown target_type: {target_type}")
        handler.save(checks, target, run_config_name, mode)

    def register_checks_handler(self, name: str, handler: ChecksHandler):
        """
        Register a new handler at runtime for new backend support.
        """
        self._checks_handlers[name] = handler

    @staticmethod
    def load_checks_from_local_file(filepath: str) -> list[dict]:
        """
        Load checks (dq rules) from a file (json or yaml) in the local filesystem.

        :param filepath: path to the file containing the checks.
        :return: list of dq rules or raise an error if checks file is missing or is invalid.
        """
        parsed_checks = DQEngineCore.load_checks_from_local_file(filepath)
        if not parsed_checks:
            raise ValueError(f"Invalid or no checks in file: {filepath}")
        return parsed_checks

    @staticmethod
    def save_checks_in_local_file(checks: list[dict], path: str):
        return DQEngineCore.save_checks_in_local_file(checks, path)

    def load_checks_from_table(self, table_name: str, run_config_name: str = "default") -> list[dict]:
        """[DEPRECATED] Use load_checks(..., source_type='table') instead."""
        return self.load_checks(table_name, "table", run_config_name)

    def save_checks_in_table(
        self, checks: list[dict], table_name: str, run_config_name: str = "default", mode: str = "append"
    ) -> None:
        """[DEPRECATED] Use save_checks(..., target_type='table') instead."""
        self.save_checks(checks, table_name, "table", run_config_name=run_config_name, mode=mode)

    def load_checks_from_workspace_file(self, workspace_path: str, run_config_name: str | None = None) -> list[dict]:
        """[DEPRECATED] Use load_checks(..., source_type='workspace_file') instead."""
        return self.load_checks(workspace_path, "workspace_file", run_config_name)

    def save_checks_in_workspace_file(
        self, checks: list[dict], workspace_path: str, run_config_name: str | None = None
    ) -> None:
        """[DEPRECATED] Use save_checks(..., target_type='workspace_file') instead."""
        self.save_checks(checks, workspace_path, "workspace_file", run_config_name)

    def load_checks_from_installation(
        self,
        run_config_name: str = "default",
        method: str = "file",
        product_name: str = "dqx",
        assume_user: bool = True,
    ) -> list[dict]:
        """
        Load checks (dq rules) from a file (json or yaml) or table defined in the installation config.
        The returning checks can be used as input for `apply_checks_by_metadata` function.

        :param run_config_name: name of the run (config) to use
        :param method: method to load checks, either 'file' or 'table'
        :param product_name: name of the product/installation directory
        :param assume_user: if True, assume user installation
        :return: list of dq rules or raise an error if checks file is missing or is invalid.
        """
        installation = self._get_installation(assume_user, product_name)
        run_config = self._load_run_config(installation, run_config_name)

        if method == "file":
            filename = run_config.checks_file or "checks.yml"
            logger.info(
                f"Loading quality rules (checks) from {installation.install_folder()}/{filename} in the workspace."
            )
            parsed_checks = self._load_checks_from_file(installation, filename)
            if not parsed_checks:
                raise ValueError(f"Invalid or no checks in workspace file: {installation.install_folder()}/{filename}")
            return parsed_checks

        table_name = run_config.checks_table
        if not table_name:
            raise ValueError("Table name must be provided either as a parameter or through run configuration.")

        return self.load_checks(table_name, "table", run_config_name)

    def save_checks_in_installation(
        self,
        checks: list[dict],
        run_config_name: str = "default",
        method: str = "file",
        product_name: str = "dqx",
        assume_user: bool = True,
    ):
        """
        Save checks (dq rules) to yaml file or table in the installation folder.
        This will overwrite existing checks file or table.

        :param checks: list of dq rules to save
        :param run_config_name: name of the run (config) to use
        :param method: method to save checks, either 'file' or 'table'
        :param product_name: name of the product/installation directory
        :param assume_user: if True, assume user installation
        """
        installation = self._get_installation(assume_user, product_name)
        run_config = self._load_run_config(installation, run_config_name)

        if method == "file":
            logger.info(
                f"Saving quality rules (checks) to {installation.install_folder()}/{run_config.checks_file} "
                f"in the workspace."
            )
            return installation.upload(run_config.checks_file, yaml.safe_dump(checks).encode('utf-8'))

        table_name = run_config.checks_table
        if not table_name:
            raise ValueError("Table name must be provided either as a parameter or through run configuration.")

        return self.save_checks_in_table(checks, table_name, run_config_name, mode="overwrite")

    def load_run_config(
        self, run_config_name: str | None = "default", assume_user: bool = True, product_name: str = "dqx"
    ) -> RunConfig:
        """
        Load run configuration from the installation.

        :param run_config_name: name of the run configuration to use
        :param assume_user: if True, assume user installation
        :param product_name: name of the product
        """
        installation = self._get_installation(assume_user, product_name)
        return self._load_run_config(installation, run_config_name)

    def _get_installation(self, assume_user, product_name):
        if assume_user:
            installation = Installation.assume_user_home(self.ws, product_name)
        else:
            installation = Installation.assume_global(self.ws, product_name)

        # verify the installation
        installation.current(self.ws, product_name, assume_user=assume_user)
        return installation

    @staticmethod
    def _load_run_config(installation, run_config_name):
        """Load run configuration from the installation."""
        config = installation.load(WorkspaceConfig)
        return config.get_run_config(run_config_name)

    @staticmethod
    def _load_checks_from_file(installation: Installation, filename: str) -> list[dict]:
        try:
            checks = installation.load(list[dict[str, str]], filename=filename)
            return deserialize_dicts(checks)
        except NotFound:
            msg = f"Checks file {filename} missing"
            raise NotFound(msg) from None
